---
ansible_python_interpreter: /usr/bin/python3
ansible_user: root
ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"

system_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

remote_user: ubuntu
