---
- name: Install docker and docker-compose to remote servers
  hosts: all
  become: yes

  tasks:
  - name: Install required system packages for docker
    apt:
      name: "{{ system_packages }}"
      state: latest

  - name: Add docker official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker repository
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
      state: present

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install docker
    apt:
      name: "{{ docker_packages }}"
      state: latest

  - name: Install docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_facts['system'] }}-{{ ansible_facts['architecture'] }}"
      dest: /usr/local/bin/docker-compose
      mode: ugo+x

  - name: Check user if exists
    shell:
      cmd: getent passwd {{ remote_user }}
    ignore_errors: yes
    register: user_exist

  - name: Add existing user to docker group
    user:
      name: "{{ remote_user }}"
      groups: docker
      append: yes
    when: user_exist.stdout != ""
